name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read # to fetch code (actions/checkout)

env:
  # We only install Chromium manually
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  Tests:
    permissions: {}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - node-version: 18
            os: windows-latest
          - node-version: 18
            os: macOS-latest
          - node-version: 18
            os: ubuntu-latest
          - node-version: 20
            os: ubuntu-latest
          - node-version: 22
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm playwright install chromium
      - run: pnpm test
        env:
          CI: true
  Lint:
    permissions: {}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: install
        run: pnpm install --frozen-lockfile
      - name: type check
        run: pnpm check
      - name: lint
        if: (${{ success() }} || ${{ failure() }}) # ensures this step runs even if previous steps fail (avoids multiple runs uncovering different issues at different steps)
        run: pnpm lint
      - name: build and check generated types
        if: (${{ success() }} || ${{ failure() }}) # ensures this step runs even if previous steps fail
        run: pnpm build && { [ "`git status --porcelain=v1`" == "" ] || (echo "Generated types have changed â€” please regenerate types locally with `cd packages/svelte && pnpm generate:types` and commit the changes after you have reviewed them"; git diff; exit 1); }
      - name: bundle
        run: |
          NODE_ENV=production pnpx esbuild \
          ./packages/svelte/src/index-client.js \
          ./packages/svelte/src/animate/index.js \
          ./packages/svelte/src/internal/client/index.js \
          ./packages/svelte/src/internal/disclose-version.js \
          ./packages/svelte/src/internal/flags/legacy.js \
          ./packages/svelte/src/internal/flags/tracing.js \
          ./packages/svelte/src/legacy/legacy-client.js \
          ./packages/svelte/src/motion/index.js \
          ./packages/svelte/src/reactivity/index-client.js \
          ./packages/svelte/src/reactivity/window/index.js \
          ./packages/svelte/src/store/index-client.js \
          ./packages/svelte/src/transition/index.js \
          ./packages/svelte/src/events/index.js \
          --bundle \
          --format=esm \
          --outdir=packages/svelte/dist \
          --minify \
          --platform=browser
          NODE_ENV=production pnpx esbuild \
          ./packages/svelte/src/index-server.js \
          ./packages/svelte/src/compiler/index.js \
          ./packages/svelte/src/internal/index.js \
          ./packages/svelte/src/internal/server/index.js \
          ./packages/svelte/src/legacy/legacy-server.js \
          ./packages/svelte/src/reactivity/index-server.js \
          ./packages/svelte/src/server/index.js \
          ./packages/svelte/src/store/index-server.js \
          --bundle \
          --format=esm \
          --outdir=packages/svelte/dist \
          --minify \
          --platform=node
      - name: gravity
        run: pnpx @gravityci/cli 'packages/svelte/dist/**/*'
        env:
          GRAVITY_TOKEN: ${{ secrets.GRAVITY_TOKEN }}

  Benchmarks:
    permissions: {}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm bench
        env:
          CI: true
